enabled_locales: ["en", "ja"]
static_pages:
  railstutorial: "http://www.railstutorial.org/"
  railsbook: "http://www.railstutorial.org/book"
  railshelp: "http://www.railstutorial.org/help"
  rubyonrails: "http://rubyonrails.org/"
  screencasts: "http://screencasts.railstutorial.org/"
layouts:
  michael: "http://www.michaelhartl.com/"
  news: "http://news.railstutorial.org/"
  raislcontact: "http://www.railstutorial.org/contact"
models:
  maxsize_name: 50
  maxsize_email: 255
  minsize_pass: 6
users:
  gravatar: "http://gravatar.com/emails"
  size_gra: 50
helpers:
  size_option: 80
controllers:
  per_page: 10
mailers:
  email_default: "noreply@example.com"
